// 'use client';
import type { Metadata } from 'next';
import { IBM_Plex_Sans } from 'next/font/google';
import './globals.css';
import { StylesLayoutShiftHider } from '@/components/StylesLayoutShiftHider';
import { DevControlForTesting } from '@/app/DevControlForTesting';

const IBM_Plex_Sans_using = IBM_Plex_Sans({
  subsets: ['latin'],
  weight: ['100', '200', '300', '400', '500', '600', '700'],
});

export const metadata: Metadata = {
  title: 'Simple form',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`superCoolBody ${IBM_Plex_Sans_using.className}`}>
        <DevControlForTesting />
        <StylesLayoutShiftHider>{children}</StylesLayoutShiftHider>
      </body>
    </html>
  );
}
